"""
盘后海外基金观察配置。

盘后观察复用盘前观察的基准、补偿仓位映射和展示项，只改变运行窗口、
缓存与输出产物。美股行情口径由执行层使用纯盘后 post 数据处理。
"""

from __future__ import annotations

from tools.configs.premarket_configs import (
    AFTERHOURS_FOOTER_BENCHMARK_KEYS,
    AFTERHOURS_FOOTER_LABELS,
    PREMARKET_BENCHMARK_SPECS,
    PREMARKET_DEFAULT_RESIDUAL_BENCHMARK_KEY,
    PREMARKET_FUND_RESIDUAL_BENCHMARK_MAP,
)


AFTERHOURS_START_HOUR_BJ = 8
AFTERHOURS_START_MINUTE_BJ = 0
AFTERHOURS_END_HOUR_BJ = 12
AFTERHOURS_END_MINUTE_BJ = 0


AFTERHOURS_BENCHMARK_SPECS = PREMARKET_BENCHMARK_SPECS
AFTERHOURS_DEFAULT_RESIDUAL_BENCHMARK_KEY = PREMARKET_DEFAULT_RESIDUAL_BENCHMARK_KEY
AFTERHOURS_FUND_RESIDUAL_BENCHMARK_MAP = PREMARKET_FUND_RESIDUAL_BENCHMARK_MAP


__all__ = [
    "AFTERHOURS_BENCHMARK_SPECS",
    "AFTERHOURS_DEFAULT_RESIDUAL_BENCHMARK_KEY",
    "AFTERHOURS_END_HOUR_BJ",
    "AFTERHOURS_END_MINUTE_BJ",
    "AFTERHOURS_FOOTER_BENCHMARK_KEYS",
    "AFTERHOURS_FOOTER_LABELS",
    "AFTERHOURS_FUND_RESIDUAL_BENCHMARK_MAP",
    "AFTERHOURS_START_HOUR_BJ",
    "AFTERHOURS_START_MINUTE_BJ",
]
