"""
缓存有效期配置。

这个文件只放“多久认为缓存仍可用”的策略常量，不读写缓存、不联网、不出图。
后续如果想调整请求频率，优先改这里，避免在多个业务脚本里到处找数字。
"""

# 普通小时桶行情缓存保留天数。主要用于盘中或短周期行情缓存裁剪。
SECURITY_HOURLY_CACHE_RETENTION_DAYS = 15

# 普通证券日线缓存保留天数。用于非指数类证券的历史缓存裁剪。
SECURITY_DAILY_CACHE_RETENTION_DAYS = 30

# 指数、基准、基金估算历史保留天数。默认保留较长，便于节假日累计和回溯。
SECURITY_INDEX_CACHE_RETENTION_DAYS = 300
FUND_ESTIMATE_HISTORY_RETENTION_DAYS = 300
ANCHOR_CACHE_STABLE_RETENTION_DAYS = 300

# 锚点行情缓存读取侧只复用 traded / closed。
# pending / missing / stale 仍会写入缓存用于排查，但不会阻止下次运行重新请求接口。

# 基金限购缓存必须严格 7 天有效，不要改成固定每周刷新。
FUND_PURCHASE_LIMIT_CACHE_DAYS = 7

# 基金持仓缓存兼容旧调用参数；实际目标季度确认逻辑仍以持仓披露窗口为准。
FUND_HOLDINGS_CACHE_DAYS = 75

# A 股交易日历文件缓存有效期。过期后才主动刷新 AkShare 日历。
A_SHARE_TRADE_CALENDAR_CACHE_DAYS = 7

# 国内 ETF RSI 只补实时点的历史缓存新鲜度阈值。
# 含义：本地 CSV 最新日期距离今天不超过这个自然日数时，可以复用历史数据并补今天实时点；
# 更旧则重拉整段历史，避免拿很旧的历史数据硬拼实时点导致 RSI 失真。
RSI_CN_ETF_REALTIME_CACHE_MAX_AGE_DAYS = 10

# 盘前实时行情文件缓存。只用于 premarket_fund.py，避免同一晚反复运行时
# 对重复持仓股和盘前基准重复请求接口；失败结果不跨运行缓存。
PREMARKET_QUOTE_CACHE_TTL_MINUTES = 15
PREMARKET_QUOTE_CACHE_RETENTION_DAYS = 1
PREMARKET_QUOTE_CACHE_MAX_ITEMS = 500

# 盘后观察实时行情文件缓存。策略与盘前保持一致，但使用独立文件，避免
# 早晚两种观察窗口的行情互相污染。
AFTERHOURS_QUOTE_CACHE_TTL_MINUTES = 15
AFTERHOURS_QUOTE_CACHE_RETENTION_DAYS = 1
AFTERHOURS_QUOTE_CACHE_MAX_ITEMS = 500

# 盘中观察实时行情文件缓存。策略与盘前保持一致，但使用独立文件，避免
# 盘前、盘中、盘后三种观察窗口的行情互相污染。
INTRADAY_QUOTE_CACHE_TTL_MINUTES = 15
INTRADAY_QUOTE_CACHE_RETENTION_DAYS = 1
INTRADAY_QUOTE_CACHE_MAX_ITEMS = 500

__all__ = [
    "SECURITY_HOURLY_CACHE_RETENTION_DAYS",
    "SECURITY_DAILY_CACHE_RETENTION_DAYS",
    "SECURITY_INDEX_CACHE_RETENTION_DAYS",
    "FUND_ESTIMATE_HISTORY_RETENTION_DAYS",
    "ANCHOR_CACHE_STABLE_RETENTION_DAYS",
    "FUND_PURCHASE_LIMIT_CACHE_DAYS",
    "FUND_HOLDINGS_CACHE_DAYS",
    "A_SHARE_TRADE_CALENDAR_CACHE_DAYS",
    "RSI_CN_ETF_REALTIME_CACHE_MAX_AGE_DAYS",
    "PREMARKET_QUOTE_CACHE_TTL_MINUTES",
    "PREMARKET_QUOTE_CACHE_RETENTION_DAYS",
    "PREMARKET_QUOTE_CACHE_MAX_ITEMS",
    "AFTERHOURS_QUOTE_CACHE_TTL_MINUTES",
    "AFTERHOURS_QUOTE_CACHE_RETENTION_DAYS",
    "AFTERHOURS_QUOTE_CACHE_MAX_ITEMS",
    "INTRADAY_QUOTE_CACHE_TTL_MINUTES",
    "INTRADAY_QUOTE_CACHE_RETENTION_DAYS",
    "INTRADAY_QUOTE_CACHE_MAX_ITEMS",
]
