"""
Futu OpenAPI based overnight overseas fund observation config.

This config is intentionally separate from the legacy night observation config.
It only affects ``futu_night_fund.py`` and the new Futu night modules.
"""

from __future__ import annotations

from tools.configs.premarket_configs import (
    FUTU_NIGHT_FOOTER_BENCHMARK_KEYS,
    FUTU_NIGHT_FOOTER_LABELS,
    PREMARKET_BENCHMARK_SPECS,
    PREMARKET_DEFAULT_RESIDUAL_BENCHMARK_KEY,
    PREMARKET_FUND_RESIDUAL_BENCHMARK_MAP,
)
from tools.paths import CACHE_DIR, NIGHT_FAILED_HOLDINGS_REPORT, SAFE_HAIWAI_NIGHT_IMAGE


FUTU_NIGHT_OPEND_HOST = "127.0.0.1"
FUTU_NIGHT_OPEND_PORT = 11111

FUTU_NIGHT_START_HOUR_BJ = 11
FUTU_NIGHT_START_MINUTE_BJ = 30
FUTU_NIGHT_END_HOUR_BJ = 16
FUTU_NIGHT_END_MINUTE_BJ = 30

FUTU_NIGHT_KLINE_BARS = 60
FUTU_NIGHT_RETURN_CACHE = CACHE_DIR / "futu_night_return_cache.json"
FUTU_NIGHT_RETURN_CACHE_TTL_MINUTES = 15
FUTU_NIGHT_RETURN_CACHE_RETENTION_DAYS = 1
FUTU_NIGHT_RETURN_CACHE_MAX_ITEMS = 500

FUTU_NIGHT_SUBSCRIBE_LIMIT = 100
FUTU_NIGHT_SUBSCRIBE_BATCH_SIZE = 90
FUTU_NIGHT_MIN_SUBSCRIBE_SECONDS = 61

FUTU_NIGHT_MAX_QUOTE_STALENESS_MINUTES = 45
FUTU_NIGHT_FUTURE_QUOTE_TOLERANCE_MINUTES = 2

FUTU_NIGHT_OUTPUT_FILE = SAFE_HAIWAI_NIGHT_IMAGE
FUTU_NIGHT_REPORT_FILE = NIGHT_FAILED_HOLDINGS_REPORT

FUTU_NIGHT_BENCHMARK_SPECS = PREMARKET_BENCHMARK_SPECS
FUTU_NIGHT_DEFAULT_RESIDUAL_BENCHMARK_KEY = PREMARKET_DEFAULT_RESIDUAL_BENCHMARK_KEY
FUTU_NIGHT_FUND_RESIDUAL_BENCHMARK_MAP = PREMARKET_FUND_RESIDUAL_BENCHMARK_MAP


__all__ = [
    "FUTU_NIGHT_BENCHMARK_SPECS",
    "FUTU_NIGHT_DEFAULT_RESIDUAL_BENCHMARK_KEY",
    "FUTU_NIGHT_END_HOUR_BJ",
    "FUTU_NIGHT_END_MINUTE_BJ",
    "FUTU_NIGHT_FOOTER_BENCHMARK_KEYS",
    "FUTU_NIGHT_FOOTER_LABELS",
    "FUTU_NIGHT_FUND_RESIDUAL_BENCHMARK_MAP",
    "FUTU_NIGHT_FUTURE_QUOTE_TOLERANCE_MINUTES",
    "FUTU_NIGHT_KLINE_BARS",
    "FUTU_NIGHT_MAX_QUOTE_STALENESS_MINUTES",
    "FUTU_NIGHT_OPEND_HOST",
    "FUTU_NIGHT_OPEND_PORT",
    "FUTU_NIGHT_OUTPUT_FILE",
    "FUTU_NIGHT_REPORT_FILE",
    "FUTU_NIGHT_RETURN_CACHE",
    "FUTU_NIGHT_RETURN_CACHE_MAX_ITEMS",
    "FUTU_NIGHT_RETURN_CACHE_RETENTION_DAYS",
    "FUTU_NIGHT_RETURN_CACHE_TTL_MINUTES",
    "FUTU_NIGHT_START_HOUR_BJ",
    "FUTU_NIGHT_START_MINUTE_BJ",
    "FUTU_NIGHT_MIN_SUBSCRIBE_SECONDS",
    "FUTU_NIGHT_SUBSCRIBE_BATCH_SIZE",
    "FUTU_NIGHT_SUBSCRIBE_LIMIT",
]
