"""
盘中海外基金观察配置。

盘中观察复用盘前观察的基准、补偿仓位映射和展示项，只改变运行窗口、
缓存与输出产物。美股行情口径由执行层使用 regular session 实时数据处理。
"""

from __future__ import annotations

from tools.configs.premarket_configs import (
    INTRADAY_FOOTER_BENCHMARK_KEYS,
    INTRADAY_FOOTER_LABELS,
    PREMARKET_BENCHMARK_SPECS,
    PREMARKET_DEFAULT_RESIDUAL_BENCHMARK_KEY,
    PREMARKET_FUND_RESIDUAL_BENCHMARK_MAP,
)


INTRADAY_START_HOUR_BJ = 22
INTRADAY_START_MINUTE_BJ = 40
INTRADAY_END_HOUR_BJ = 2
INTRADAY_END_MINUTE_BJ = 0


INTRADAY_BENCHMARK_SPECS = PREMARKET_BENCHMARK_SPECS
INTRADAY_DEFAULT_RESIDUAL_BENCHMARK_KEY = PREMARKET_DEFAULT_RESIDUAL_BENCHMARK_KEY
INTRADAY_FUND_RESIDUAL_BENCHMARK_MAP = PREMARKET_FUND_RESIDUAL_BENCHMARK_MAP


__all__ = [
    "INTRADAY_BENCHMARK_SPECS",
    "INTRADAY_DEFAULT_RESIDUAL_BENCHMARK_KEY",
    "INTRADAY_END_HOUR_BJ",
    "INTRADAY_END_MINUTE_BJ",
    "INTRADAY_FOOTER_BENCHMARK_KEYS",
    "INTRADAY_FOOTER_LABELS",
    "INTRADAY_FUND_RESIDUAL_BENCHMARK_MAP",
    "INTRADAY_START_HOUR_BJ",
    "INTRADAY_START_MINUTE_BJ",
]
