"""
RSI 图表配置。

维护影响：
- 每一项配置对应一张 RSI 分析图及其输出路径。
- 新增或停用关注标的时，优先改这里；`stock_analysis.py` 只负责执行配置。
"""

RSI_ANALYSIS_CONFIGS = [
    {
        "name": "纳斯达克综合指数",
        "image": "output/nasdaq_analysis.png",
        "kwargs": {
            "symbol": ".IXIC",
            "display_name": "纳斯达克综合指数",
            "days": 180,
            "output_file": "output/nasdaq_analysis.png",
            "daily_rsi_window": 9,
            "daily_rsi_high": 80,
            "daily_rsi_low": 32,
            "weekly_rsi_window": 9,
            "weekly_rsi_high": 78,
            "weekly_rsi_low": 35,
            "monthly_rsi_window": 9,
            "monthly_rsi_high": 77,
            "monthly_rsi_low": 40,
            "show_daily_signals": True,
            "show_weekly_signals": True,
            "show_monthly_signals": True,
            "print_signal_dates_flag": False,
            "save_signal_table": False,
            "signal_table_file": "output/nasdaq_rsi_signal_table.png",
            "return_signals": True,
            "show_plot": False,
        },
    },
    {
        "name": "红利低波华泰ETF",
        "image": "output/honglidibo_analysis.png",
        "use_realtime_param": True,
        "kwargs": {
            "symbol": "512890",
            "display_name": "红利低波华泰ETF",
            "days": 300,
            "output_file": "output/honglidibo_analysis.png",
            "daily_rsi_window": 9,
            "daily_rsi_high": 77,
            "daily_rsi_low": 30,
            "weekly_rsi_window": 9,
            "weekly_rsi_high": 75,
            "weekly_rsi_low": 35,
            "monthly_rsi_window": 9,
            "monthly_rsi_high": 70,
            "monthly_rsi_low": 45,
            "show_daily_signals": True,
            "show_weekly_signals": True,
            "show_monthly_signals": True,
            "print_signal_dates_flag": False,
            "save_signal_table": False,
            "signal_table_file": "output/honglidibo_table.png",
            "cache_dir": "cache",
            "retry": 3,
            "use_cache": True,
            "allow_eastmoney": False,
            "return_signals": True,
            "show_plot": False,
        },
    },
    {
        "name": "上证指数ETF：510210",
        "image": "output/shangzheng_analysis.png",
        "use_realtime_param": True,
        "kwargs": {
            "symbol": "510210",
            "display_name": "上证指数ETF：510210",
            "days": 300,
            "output_file": "output/shangzheng_analysis.png",
            "daily_rsi_window": 9,
            "daily_rsi_high": 78,
            "daily_rsi_low": 30,
            "weekly_rsi_window": 9,
            "weekly_rsi_high": 80,
            "weekly_rsi_low": 35,
            "monthly_rsi_window": 9,
            "monthly_rsi_high": 75,
            "monthly_rsi_low": 40,
            "show_daily_signals": True,
            "show_weekly_signals": True,
            "show_monthly_signals": True,
            "print_signal_dates_flag": False,
            "save_signal_table": False,
            "signal_table_file": "output/shangzheng_table.png",
            "cache_dir": "cache",
            "retry": 3,
            "use_cache": True,
            "allow_eastmoney": False,
            "return_signals": True,
            "show_plot": False,
        },
    },
    {
        "name": "德国DAX：159561",
        "image": "output/germany_dax.png",
        "use_realtime_param": True,
        "kwargs": {
            "symbol": "159561",
            "display_name": "德国DAX：159561",
            "days": 300,
            "output_file": "output/germany_dax.png",
            "daily_rsi_window": 9,
            "daily_rsi_high": 75,
            "daily_rsi_low": 30,
            "weekly_rsi_window": 9,
            "weekly_rsi_high": 80,
            "weekly_rsi_low": 35,
            "monthly_rsi_window": 9,
            "monthly_rsi_high": 75,
            "monthly_rsi_low": 40,
            "show_daily_signals": True,
            "show_weekly_signals": True,
            "show_monthly_signals": True,
            "print_signal_dates_flag": False,
            "save_signal_table": False,
            "signal_table_file": "output/germany_dax_table.png",
            "cache_dir": "cache",
            "retry": 3,
            "use_cache": True,
            "allow_eastmoney": False,
            "return_signals": True,
            "show_plot": False,
        },
    },
]


__all__ = ["RSI_ANALYSIS_CONFIGS"]
